[settings]
cargo_binstall = true
experimental = true
legacy_version_file = true
not_found_auto_install = false
pipx_uvx = true
idiomatic_version_file_enable_tools = [
  "ruby",
  "rust",
  "python",
  "node",
  "go",
  "terraform",
  "yarn",
]

[settings.status]
show_env = true
show_tools = false

[settings.npm]
bun = true

[settings.pipx]
# Allow mise to install pipx packages without manual installation of pipx.
uvx = true

[settings.ruby]
ruby_install = true

[tools]
biome = "latest"
bun = "latest"
cargo-binstall = "latest"
cosign = "3"
chezmoi = "2"
go = "latest"
gum = "latest"
hadolint = "latest"
hivemind = "latest"
java = "lts"
just = "latest"
kubectl = "latest"
lazygit = "latest"
node = "lts"
python = "3.13.7"
ruby = "3.4.7"
rust = { version = "latest", components = "rust-analyzer,rust-src" }
shellcheck = "latest"
shfmt = "latest"
usage = "latest"
uv = "latest"
vale = "latest"
watchexec = "latest"

# Rust
"aqua:AlexanderGrooff/mermaid-ascii" = "latest"
"aqua:golangci/golangci-lint" = "latest"
"aqua:sharkdp/hexyl" = "latest"
"aqua:tldr-pages/tlrc" = "latest"
"cargo:ast-grep" = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-about" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:cargo-generate" = "latest"
"cargo:cargo-info" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-update" = "latest"
"cargo:eza" = "latest"
"cargo:git-absorb" = "latest"
"cargo:git-cliff" = "latest"
"cargo:gitu" = "latest"
"cargo:jj-cli" = "latest"
"cargo:sqlx-cli" = "latest"
"cargo:tokei" = "latest"
"cargo:topgrade" = "latest"

# Node.js
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@herb-tools/language-server" = "latest"
"npm:@sourcegraph/amp" = "latest"
"npm:@openai/codex" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint_d" = "latest"
"npm:jsvu" = "latest"
"npm:knip" = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:pnpm" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-css-languageserver-bin" = "latest"
"npm:vscode-json-languageserver" = "latest"
"npm:yalc" = "latest"
"npm:yaml-language-server" = "latest"
"npm:yarn" = "latest"

# Python
# "pipx:lsp-devtools" = "latest"
"pipx:llm" = "latest"
"pipx:pdm" = "latest"
"pipx:pgcli" = "latest"
"pipx:ruff" = "latest"
"pipx:yt-dlp" = "latest"
"pipx:yubikey-manager" = "latest"
