---
gui:
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
git:
  parseEmoji: true
  commit:
    autoWrapCommitMessage: true
    autoWrapWidth: 72
  pagers:
    - pager: delta --paging=never
os:
  editPreset: "nvim"
